### ISSUE TITLE
Appropriate repo for nearby resources?

### ISSUE THREAD

**Issue by naconner** [liberland/resources#1]
Would this be an appropriate repo for information on nearby resources in Serbia and Croatia?

*E.g.*, surrounding towns, port access, airports, property rentals, boats, storefronts for basic supplies, visa requirements, etc.

**Comment by burningtree** [comment]
Yes, this repo is created for all links and documents related to Liberland. Any useful information is welcome.

**Comment by naconner** [comment]
Great. I'll continue curating.
